name: Test and Deploy API Sentiment Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Étape 3 : Créer un environnement virtuel
      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      # Étape 4 : Installer les dépendances
      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install joblib scikit-learn

      # Étape 5 : Vérification des artefacts nécessaires
      - name: Check for Model Files
        run: |
          test -f models/pca_model.pkl || (echo "PCA model file is missing!" && exit 1)
          test -d models/mlflow_model/LogisticRegression_model || (echo "MLflow model folder is missing!" && exit 1)

      # Étape 6 : Exécuter les tests
      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest tests/ --maxfail=5 --disable-warnings
