name: Test and Deploy API Sentiment Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Liste des fichiers pour vérification
      - name: List Repository Files
        run: ls -al

      # Étape 3 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Étape 4 : Installation des dépendances sans environnement virtuel
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r api_sentiment_analysis/requirements.txt
          pip install joblib scikit-learn

      # Étape 5 : Vérification des modèles et fichiers nécessaires
      - name: Verify Models
        run: |
          test -f api_sentiment_analysis/models/pca_model.pkl || (echo "PCA model file is missing!" && exit 1)
          test -d api_sentiment_analysis/models/mlflow_model || (echo "MLflow model folder is missing!" && exit 1)

      # Étape 6 : Exécution des tests unitaires
      - name: Run Tests
        run: |
          pytest api_sentiment_analysis/tests/ --maxfail=5 --disable-warnings

      # Étape 7 : Nettoyage des fichiers temporaires
      - name: Clean Temporary Files
        run: |
          find . -name "__pycache__" -exec rm -rf {} +
          find . -name "*.pyc" -exec rm -rf {} +
          find . -name "*.pyo" -exec rm -rf {} +

      # Étape 8 : Déploiement sur Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "openclassrooms-sentiment-analysis-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./api_sentiment_analysis
