name: Test and Deploy API Sentiment Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Working Directory
        run: cd api_sentiment_analysis

      - name: List Repository Files
        run: ls -al

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install joblib scikit-learn
        working-directory: ./api_sentiment_analysis

      # Étape 5 : Vérification des artefacts nécessaires
      - name: Check for Model Files
        run: |
          test -f models/pca_model.pkl || (echo "PCA model file is missing!" && exit 1)
          test -d models/mlflow_model/LogisticRegression_model || (echo "MLflow model folder is missing!" && exit 1)

      # Étape 6 : Exécuter les tests
      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest tests/ --maxfail=5 --disable-warnings
