name: Test API Sentiment Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.15"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Mock PCA File
        run: |
          mkdir -p models
          echo "Mock PCA file" > models/pca_model.pkl

      - name: Run Tests
        run: |
          pytest tests/ --maxfail=5 --disable-warnings
