name: Test and Deploy API Sentiment Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Liste des fichiers pour vérification
      - name: List Repository Files
        run: ls -al

      # Étape 3 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Étape 4 : Création et activation d'un environnement virtuel nommé 'antenv'
      - name: Create Virtual Environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
        working-directory: ./api_sentiment_analysis

      # Étape 5 : Installation des dépendances
      - name: Install Dependencies
        run: |
          source antenv/bin/activate
          pip install -r requirements.txt
          pip install joblib scikit-learn
        working-directory: ./api_sentiment_analysis

      # Étape 6 : Vérification des modèles et fichiers nécessaires
      - name: Verify Models
        run: |
          test -f models/pca_model.pkl || (echo "PCA model file is missing!" && exit 1)
          test -d models/mlflow_model || (echo "MLflow model folder is missing!" && exit 1)
        working-directory: ./api_sentiment_analysis

      # Étape 7 : Exécution des tests unitaires
      - name: Run Tests
        run: |
          source antenv/bin/activate
          pytest tests/ --maxfail=5 --disable-warnings
        working-directory: ./api_sentiment_analysis

      # Étape 8 : Nettoyage des fichiers temporaires
      - name: Clean Temporary Files
        run: |
          find . -name "__pycache__" -exec rm -rf {} +
          find . -name "*.pyc" -exec rm -rf {} +
          find . -name "*.pyo" -exec rm -rf {} +
        working-directory: ./api_sentiment_analysis

      # Étape 9 : Déploiement sur Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "openclassrooms-sentiment-analysis-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./api_sentiment_analysis
